[workspace]
members = ["rfsm-macros"]
resolver = "3"

[package]
name = "rfsm"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "Table-first finite state machines for Rust"
repository = "https://github.com/mudake-rs/rfsm"
include = [
    "/src/**/*.rs",
    "/examples/**/*.rs",
    "/tests/**/*.rs",
    "/Cargo.toml",
    "/README.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
]

[dependencies]
rfsm-macros = { version = "0.1.0", path = "rfsm-macros" }
