[package]
name = "rfsm-macros"
version = "0.2.1"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "Proc macros for the rfsm crate"
repository = "https://github.com/mudake-rs/rfsm"
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
]

[lib]
proc-macro = true

[features]
default = []
serde = []

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
